### Program to calculate the eigen values and eigen vector  of a square array

In [15]:
def det(matrix):
    """
    The function det(A) takes any matrix in list form. For example 
    A=[[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]]
    det(A) will give the determinant of square matrix A. For, non square matrix, it will raise an error such that the matrix
    is not a square matrix.
    """
    # Assume determinant as determ and 0 as its initial value.
    determ=0
    # Import numpy module as np 
    import numpy as np
    # If input array is a list like shown above, convert it to numpy array
    matrix=np.array(matrix)
    ## Now we will check if the matrix is square or not. If matrix is a square matyrix then its determinant
    # can be computed else the function should raise an error.
    # matrix.shape gives dimension of array in format like [number of rows, number of columns]
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError('The matrix is not a square matrix. Determinant can be computed only for a square matrix.')
    
    elif matrix.shape[0]==matrix.shape[1]:
    
    # If matrix is of dimension 2 by 2  [[a b], [c d]] then the determinant is just ad-bc
        if matrix.shape[0]==2:
            determ = matrix[0, 0]*matrix[1, 1]-matrix[0, 1]*matrix[1, 0]  
        # if the matirx is of higher diemnsions then we use recursion to calculate the determinant. 
        
        elif matrix.shape[0]>2:   # Check if the dimensions are greater than 2 x 2 
            for i in range(matrix.shape[0]):
                minor = np.delete(np.delete(matrix, 0, axis=0), i, axis=1)  # Calculate the minor 
                determ += (-1)**i * matrix[0, i] * det(minor)     # calculate determinant using recursion 
    
    return (determ)   # return the determ i.e., determinant 

def eigenSym(A):
    """This functions calculates the eigen values symbolically using sympy module
    The draw back of using solveset is that it does not show the multiplicity of roots. However, it is based on the 
    mathematics behind the eigen values calculation"""
    from sympy import solveset, Symbol  
    import numpy as np
    A = np.array(A)
    if A.shape[0] != A.shape[1]:
        raise ValueError('The matrix is not a square matrix. Eigen values can be computed only for a square matrix.')
    
    elif A.shape[0]==A.shape[1]:
        x=Symbol('x')        
        xi = x*np.identity(A.shape[0], dtype=int)
        Axi = A-xi
        det_Axi = det(Axi) 
        eigen_values= solveset(det_Axi, x)
        return(eigen_values)

In [17]:
A=[[-5, -10, -5], 
    [2, 14, 2],
   [-4, -8, 6]
]
eigenSym(A)

{-5, 10}

In [18]:
#for i in range(A.shape[0]):
#    minor = np.delete(np.delete(A, 0, axis=0), i, axis=1)
#    print(minor, end = '   ')
#    print(A[0, i])

In [19]:
import warnings
warnings.filterwarnings('ignore')
def eigen_val_vec(A):
    """This program utilizes the numpy.roots() to calculate the roots instead of sympy.solsets()"""
    from sympy import solveset, Symbol
    import numpy as np
    
    A = np.array(A)
    eigen_vec=np.zeros((A.shape[0], A.shape[0]))
    polynomial = np.poly(A)
    eigen_vals = np.roots(polynomial)
    for i in range(A.shape[0]):
        shifted_matrix = A-eigen_vals[i]*np.eye(A.shape[0])
        _,vec = np.linalg.qr(shifted_matrix)
        eigen_vec[:, i]=vec[:, -1]
    return(eigen_vals, eigen_vec)
eigen_values, eigen_vectors=eigen_val_vec(A)
print(f"Eigen values are: {eigen_values}")
print(f"Eigen_vectors are:\n {eigen_vectors}")

Eigen values are: [10.+2.27759435e-07j 10.-2.27759435e-07j -5.+0.00000000e+00j]
Eigen_vectors are:
 [[ 6.06932737e+00  6.06932737e+00 -8.94427191e+00]
 [-2.85714286e+00 -2.85714286e+00 -8.36660027e+00]
 [ 8.24277415e-15  8.24277415e-15  1.37124257e-14]]


### Program to to compute the factor of a given array by Singular Value Decomposition


In [20]:
import numpy as np

def svd(matrix, epsilon=1e-10):
    # Compute A^T * A and A * A^T
    A_transpose_A = np.dot(matrix.T, matrix)
    A_A_transpose = np.dot(matrix, matrix.T)

    # Find eigenvalues and eigenvectors of A^T * A and A * A^T
    eigenvalues_U, U = np.linalg.eigh(A_transpose_A)
    eigenvalues_V, V = np.linalg.eigh(A_A_transpose)

    # Sort eigenvalues and eigenvectors in descending order
    sort_indices_U = np.argsort(eigenvalues_U)[::-1]
    sort_indices_V = np.argsort(eigenvalues_V)[::-1]
    U = U[:, sort_indices_U]
    V = V[:, sort_indices_V]
    eigenvalues_U = eigenvalues_U[sort_indices_U]
    eigenvalues_V = eigenvalues_V[sort_indices_V]

    # Calculate the singular values from the eigenvalues
    singular_values = np.sqrt(eigenvalues_U)

    # Calculate the pseudoinverse of singular values
    singular_values_inv = np.where(singular_values > epsilon, 1.0 / singular_values, 0)

    # Calculate the matrices U, Σ, and V^T
    U = U[:, :len(singular_values)]
    Sigma = np.diag(singular_values)
    V = V[:, :len(singular_values)].T

    return U, Sigma, V

# Example usage:
if __name__ == "__main__":
    # Replace the following matrix with your input array
    matrix = np.array([[1, 2], [3, 4], [5, 6]])

    U, Sigma, V = svd(matrix)

    print("Matrix U:")
    print(U)

    print("\nMatrix Σ:")
    print(Sigma)

    print("\nMatrix V^T:")
    print(V)


Matrix U:
[[ 0.61962948 -0.78489445]
 [ 0.78489445  0.61962948]]

Matrix Σ:
[[9.52551809 0.        ]
 [0.         0.51430058]]

Matrix V^T:
[[-0.2298477  -0.52474482 -0.81964194]
 [-0.88346102 -0.24078249  0.40189603]]


### Program to calculate the determinant of a given square array

In [21]:
def det(matrix):
    """
    The function det(A) takes any matrix in list form. For example 
    A=[[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]]
    det(A) will give the determinant of square matrix A. For, non square matrix, it will raise an error such that the matrix
    is not a square matrix.
    """
    # Assume determinant as determ and 0 as its initial value.
    determ=0
    # Import numpy module as np 
    import numpy as np
    # If input array is a list like shown above, convert it to numpy array
    matrix=np.array(matrix)
    ## Now we will check if the matrix is square or not. If matrix is a square matyrix then its determinant
    # can be computed else the function should raise an error.
    # matrix.shape gives dimension of array in format like [number of rows, number of columns]
    if matrix.shape[0] != matrix.shape[1]:
        raise ValueError('The matrix is not a square matrix. Determinant can be computed only for a square matrix.')
    
    elif matrix.shape[0]==matrix.shape[1]:
    
    # If matrix is of dimension 2 by 2  [[a b], [c d]] then the determinant is just ad-bc
        if matrix.shape[0]==2:
            determ = matrix[0, 0]*matrix[1, 1]-matrix[0, 1]*matrix[1, 0]  
        # if the matirx is of higher diemnsions then we use recursion to calculate the determinant. 
        
        elif matrix.shape[0]>2:   # Check if the dimensions are greater than 2 x 2 
            for i in range(matrix.shape[0]):
                minor = np.delete(np.delete(matrix, 0, axis=0), i, axis=1)  # Calculate the minor 
                determ += (-1)**i * matrix[0, i] * det(minor)     # calculate determinant using recursion 
    
    return (determ)   # return the determ i.e., determinant 


In [22]:
help(det)

Help on function det in module __main__:

det(matrix)
    The function det(A) takes any matrix in list form. For example 
    A=[[1, 2, 3],
       [3, 4, 5],
       [5, 6, 7]]
    det(A) will give the determinant of square matrix A. For, non square matrix, it will raise an error such that the matrix
    is not a square matrix.



In [23]:
A =[[2, -4],   
     [-1, -1]]
try:
    determinant = det(A)
    print(f"Determinant = {determinant}")
except ValueError as error:
    print(error)


Determinant = -6
